config: runtime: boot: Use latest kselftest rootfs to avoid tap issue
Update the kselftest rootfs URL to the latest one which includes tappy,
and is thus able to parse the kselftest results without throwing an
error:

ModuleNotFoundError: No module named 'tap'

Signed-off-by: Nícolas F. R. A. Prado <nfraprado@collabora.com>