kernelci/cli/docker: improve error logging for build failure
Improve error logging for `kci docker build` command.

In case of a failure to clone a github repository, the logs were as
below if `verbose` is enabled:
```
docker.errors.BuildError: The command '/bin/sh -c git clone --depth=1
$core_url /tmp/kernelci-core' returned a non-zero code: 128
```

Improved it to get specific error message while using `verbose`
mode i.e.:
```
Cloning into '/tmp/kernelci-core'...
fatal: could not read Username for 'https://github.com': No such device
or address
```

Instead of raising `BuildError` directly on build failures from
`kci docker build` command, move it to `try-except` block to get
detailed error logs from `Exception` object.

Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>