roofs: deqp-runner: use rm -rf for rust cleanup
Use rm -rf for rust cleanup instead of rustup uninstal to
avoid the below error for armhf builds,

error: could not remove 'rustup_home' directory: '/root/.rustup':
Value too large for defined data type (os error 75)

Signed-off-by: Vignesh Raman <vignesh.raman@collabora.com>