config/docker: add workaround patch for gcc-10 plugins
Add temporary fix for failing builds with Debian gcc-10.  The error
can be seen with allmodconfig or when gcc plugins are enabled.  For
example:

  https://storage.kernelci.org/mainline/master/v5.17-rc7/x86_64/allmodconfig/gcc-10/logs/build-errors.log
  /usr/lib/gcc/x86_64-linux-gnu/10/plugin/include/config/i386/i386.h:2500:10: fatal error: common/config/i386/i386-cpuinfo.h: No such file or directory
  /usr/lib/gcc/x86_64-linux-gnu/10/plugin/include/config/i386/i386.h:2500:10: fatal error: common/config/i386/i386-cpuinfo.h: No such file or directory

Add patch proposed in Debian's bug tracking system since it won't be
fixed in the Debian package:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980609#72

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>