lava/cros-flash: raise exception when no device_id
Raise an exception from the Jinja2 template when no device_id is set
while generating a cros-flash job definition.  This is required in
order to deterministically flash a particular device and not any
random one.

If no --device-id option is passed to kci_test, this exception is now
raised:

  Exception: No device id provided

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>