rootfs/chromiumos: Add EC build workarounds
octopus and hatch require a small patch (workaround) at current
moment, otherwise build fails with this error:

    No boards found; assuming we're building for a fuzzer.
    ERROR: chromeos-base/chromeos-ec-0.0.2-r12066::chromiumos failed (compile phase):
    No EC boards found.

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>