Revert "build.py: updates for MIPS"
This reverts commit 8d7d046a014b10502f62feb0782dd1dc0e64c838.

This patch works with gcc-7 but not with the gcc-6.3.0 special version
we're using, the command to get the compiler version doesn't work:

Traceback (most recent call last):
  File "/home/buildslave/workspace/workspace/kernel-build@6/kernelci-core/build.py", line 247, in <module>
      cc_version = subprocess.check_output(cc_cmd, shell=True).splitlines()[0]
        File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
	    raise CalledProcessError(retcode, cmd, output=output)
	    subprocess.CalledProcessError: Command 'mips-linux-gnu-gcc --version 2>&1' returned non-zero exit status 127

Reverting it for now until we've confirmed that the 6.3.0 can be used
with all MIPS variants.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>