config/docker: Add missing yaml/requests python dependency
When running kci_rootfs from a freshly built kernelci/debos docker, I got:
/kci_rootfs --arch riscv64 -h
Traceback (most recent call last):
  File "/kernelci-core/./kci_rootfs", line 23, in <module>
    import kernelci.rootfs
  File "/kernelci-core/kernelci/rootfs.py", line 20, in <module>
    from kernelci.storage import upload_files
  File "/kernelci-core/kernelci/storage.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

./kci_rootfs --arch riscv64
Traceback (most recent call last):
  File "/kernelci-core/./kci_rootfs", line 24, in <module>
    import kernelci.config.rootfs
  File "/kernelci-core/kernelci/config/__init__.py", line 20, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

So lets adds missing python package.

Signed-off-by: Corentin Labbe <clabbe@baylibre.com>