CHROMEOS Add EC build workarounds for octopus and hatch
octopus and hatch require small patch (workaround) at current moment, otherwise build fail with error:

    No boards found; assuming we're building for a fuzzer.
    ERROR: chromeos-base/chromeos-ec-0.0.2-r12066::chromiumos failed (compile phase):
    No EC boards found.

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>