(pyproject.toml) Fix pip install
We need to fix staging failure.

```
  Building wheel for bson (setup.py): started
  Building wheel for bson (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      [end of output]
```

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>