setup: add all dependencies to setup.py
When installing kernelci via pip, all the dependencies are
not properly installed:

~ ϟ kci_build --help
Traceback (most recent call last):
  File "/home/mkorpershoek/.local/bin/kci_build", line 23, in <module>
    import kernelci.build
  File "/home/mkorpershoek/.local/lib/python3.8/site-packages/kernelci/build.py", line 32, in <module>
    import kernelci.elf
  File "/home/mkorpershoek/.local/lib/python3.8/site-packages/kernelci/elf.py", line 24, in <module>
    import elftools.elf.constants as elfconst
ModuleNotFoundError: No module named 'elftools'

~ ϟ pip3 show kernelci
Name: kernelci
Version: 1.0
Summary: KernelCI core functions
Home-page: https://github.com/kernelci/kernelci-core
Author: kernelci.org
Author-email: kernelci@groups.io
License: UNKNOWN
Location: /home/mkorpershoek/.local/lib/python3.8/site-packages
Requires: pyyaml, jinja2
Required-by:

To fix this, sync back all the dependencies from requirements.txt
into setup.py

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>