requirements: replace `bson` with `motor`
While trying to run `api` built with `kernelci` fragment,
I received below error:
```
  File "/usr/local/lib/python3.11/site-packages/api/main.py", line 27, in <module>
    from pymongo.errors import DuplicateKeyError
  File "/usr/local/lib/python3.11/site-packages/pymongo/__init__.py", line 90, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/local/lib/python3.11/site-packages/pymongo/collection.py", line 40, in <module>
    from bson.raw_bson import RawBSONDocument
  File "/usr/local/lib/python3.11/site-packages/bson/raw_bson.py", line 57, in <module>
    from bson import _get_object_size, _raw_to_dict
ImportError: cannot import name '_get_object_size' from 'bson' (/usr/local/lib/python3.11/site-packages/bson/__init__.py)
^CINFO:     Stopping reloader process [1]
```
The issue is `bson` was being `installed` due to `kernelci` package
after the installation of `pymongo` with `kernelci-api` package.
`pymongo` comes with its own `bson` and is not compatible if `bson`
is installed externally and treat it as a third-party package.
Detailed summary of the root cause can be found at:
https://github.com/kernelci/kernelci-core/pull/2485#issuecomment-2029743842
Replace the package with `motor` to resolve the issue and make it consistent with
`api` requirements.

Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>